### PR TITLE
Fixed bug in minify pre-setup function

### PR DESCRIPTION
**Pull request by GeyseR**
Collect all files from collection instead of last one only

Compressed files from more than one file are broken in 4.3.0 release.

### CODE REVIEW

**Comment by codingjoe** [comment]
can you run the setup file using sdist to proove the fucntionaly

**Comment by GeyseR** [comment]
Hi @codingjoe!
I've attached new minified versions builede after `setup.py sdist` commnad

**Comment by GeyseR** [comment]
@codingjoe @applegrew  
Guys, do you plan to release fixed version on PyPi? Currently only broken 4.3.0 version is available as edge version.

**Comment by applegrew** [comment]
@GeyseR Done. My net died yesterday when I was about to do that.

**Pull request merged**
