### PR TITLE
publish umd to npm

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by codingjoe** [comment]
@graingert thanks for the contribution. I think I currently don't understand the use case good enough. Could you elaborate a bit more on what you are trying to achieve here? Best -joe

**Comment by graingert** [comment]
I want to manage as many static assets with webpack as possible

**Comment by codingjoe** [comment]
I am split. I don't really know if I to introduce NPM support. If you find support for that ticket by other frequent contributors I will merge it. Currently I am undecided. You'd also find someone to review this. I have 0 experience with NPM.

**Comment by graingert** [comment]
it's `npm`

**Comment by codingjoe** [comment]
And don't get me wrong. I don't want to discourage you. But this package has a large user base, adding new things is always trick, since it has to be maintained for a really long time.

**Comment by graingert** [comment]
@codingjoe what about a PR that just adds the MAUAL_MEDIA settings/

**Comment by graingert** [comment]
@codingjoe also you can get the JS via the unpkg cdn now:

```html
<script src="https://unpkg.com/django-select2@^0.0.1"></script>
```

**Comment by codingjoe** [comment]
@graingert I see that you have already taken the liberty to register the package on npmjs.org, of course you are free to do that. BTW, the version is wrong. That could be slightly misleading.

I don't see a use case for a manual media setting other than yours. Even in this case I would probably suggest to just override the `media` attribute. Subclassing would be my go to solution to add or change the default behavior, not adding more settings.

Regarding the npm package, you're use case still seems to be extremely narrow. Again I don't want to discourage you, but you have to understand that I can not accept every new feature request. 

I will close this for now, but again if you find more backing for your feature I am happy to revisit this topic.

Best
-Joe

**Comment by codingjoe** [comment]
I'm not saying that webpack is a narrow use case, it's service this particular JS file via webpack. (I know that because you are the first one to ask ;)

See, this package is build to work out of the box and to be simple. If you want to extend it, we tend to add a documentation on how to do that, rather than adding more code.

So I am all in to help you build your solution (tho I think I don't need to, because you got that already covered). I am also happy to accept new documentation that describes best practices and how to implement serving via webpack.

Just in case I haven't said it enough. I really appreciated your contributions and don't want to discourage you.

**Comment by graingert** [comment]
@codingjoe would you accept a PR with just the UMD and package.json changes?

**Comment by graingert** [comment]
@codingjoe did you see npm-publish-git-tag?

**Pull request closed without merging**
