### PR TITLE
Fix HeavySelect2TagWidget to respect custom attrs and default overrides

### PR DESCRIPTION
**Pull request by rizumu**

### CODE REVIEW

**Comment by codingjoe** [comment]
@rizumu good catch. Please check the error.
Plus you might want to use:
```python
attrs = super()
defaults = {
    'data-my-attr': True,
    'data-my-other-attr': "foo",
} 
defaults.update(attrs)
return defaults
```

**Comment by rizumu** [comment]
@codingjoe I fixed the broken test by setting the default value on `self.attrs` before calling super. I also added a test to ensure custom attrs take precedence and squashed my commits.

**Comment by codingjoe** [comment]
hey @rizumu, do you set `self.attrs` why not just update the super response?
Sorry it took so long I was on vacation.

**Comment by rizumu** [comment]
@codingjoe Simply to match the code-style used elsewhere in this file.

**Comment by rizumu** [comment]
@codingjoe I thought you were asking why I chose `setdefault` over `.update()` but I realize you may have been asking something else. If so could you explain more cause I don't quite understand.

**Comment by codingjoe** [comment]
```python
self.attrs.setdefault('foo', 'bar')
return super()
```
vs.
```python
attrs = super()
attrs.setdefault('foo', 'bar')
return attrs
```

**Comment by rizumu** [comment]
@codingjoe In there lies the bug that is being fixed here. The default needs to be set before calling super, otherwise it isn't a default that overrides defaults further down the chain. Since this is the highest level class that would be imported, we want to use its default before checking if a parent class has a default set for the same attribute.

**Comment by rizumu** [comment]
In other words, if setdefault is called after getting attrs from super, and super defines its own default, then the default in the current method would be ignored, cause it is already set by super. 

See: https://github.com/applegrew/django-select2/blob/master/django_select2/forms.py#L83

**Comment by codingjoe** [comment]
Released in 5.2.1

**Pull request closed without merging**
