### PR TITLE
Removed own caching solution in favour of django caching

### PR DESCRIPTION
**Pull request by codingjoe**
The old multiprocessing support was hard to maintain.
Since signing and caching are part of `django.core`
there is really no need to stick to our own solution.

As a result multimachine support and security are now always in place.
Fields are stored in Django's cache. The default cache used by select2
is called 'default' but can be cachanged overwriting the setting
`SELECT2_CACHE_BACKEND`.

Recommended cache backends are memcached, redis or a DB-cache.

### CODE REVIEW

**Comment by codingjoe** [comment]
@applegrew I made a little progress getting rid of legacy code.
I hope you like it. This requires at least a new minor version.
It doesn't break old integrations, tho it behaves differently.

**Comment by applegrew** [comment]
If we can cut down on flab that is great! In this case I tried to support one usecase where we do not want to send any meaningful info in the auto id, even when encrypted. But yes that was an overkill, so I am okay to remove that. My below comments might not be 100% accurate since I don't remember the full code now.

However, I see a problem with `cache.set(cache_key, self)`. First, I am not sure if this will be very efficient to serialize and de-serialize the class object. The deserialization will happen every few keystrokes. Second, think of multiple processor world. Old users when they update to this version in production and who do not use django cache, their code might start to not work intermittently. Since, in that case the django processes will be using private memory caches. So an auto field might have been rendered by one process, but is being served by another process.

Also, when we remove options, we should document that to help old users. Otherwise they might later recall like "there used be some option like multi.. processor something, but I can't find it in docs". It is better to let them know that indeed there used be such an option, but that is gone since version X.

**Comment by codingjoe** [comment]
Good points, I will add proper deprecation with full removal in version 5. Including upgrade documentation of course.
I will also think about how to do better serialisation of the Field instance, but I need to have a closer look into django's cache first.

I like that you're with me. We really need to cut down on code that isn't part of the core package.
I'll keep you posted on updates.

**Comment by codingjoe** [comment]
@applegrew I looked into some of your points.
First, Django's cache seems to be fast efficient enough to cache whatever object. We shouldn't care.
Secondly, the current solution isn't multinode save unless you use memcached. Same goes for anything really. You'll always need shared memory.

I will refactor my PR so it throws proper deprecation warnings for the settings, for a removal in version 5. Also I will already use previous settings, to create a new cache backend on the fly if possible.
Meaning it will always run on the new code, no matter what.

That seems the easiest solution to me.

**Comment by applegrew** [comment]
Sounds good.

**Comment by codingjoe** [comment]
@applegrew I found another problem. I don't have any handling should the cache be flushed for any reason. I made sure that the keys don't expire, but you could still flush the entire backend.

There isn't really a way around it and my new implementation allows creating new field during runtime. Something I was trying to do for a while. I think the only workaround now, would be to create a separate cache backend, that can not be flushed by accident.
What do you think?

If you're fine with that, I'll make sure this risk will be reflected in the documentation.

**Comment by applegrew** [comment]
Well cache shouldn't be the source of truth. For production scenario a more
robust implementation is needed. Maybe the class needs to be pickled and
saved into DB. In case of cache miss the DB needs to be queried.

However, best would be if there is a possibility to create a new field
instance. As far as I recall only one auto field instance is used per class
to serve the ajax call. So, I think there shouldn't be a problem to auto
instantiate a field class, provided the field key has enough info.

**Comment by codingjoe** [comment]
@applegrew I agree. The cache is an unreliable source of truth. I could serialise all data that is needed by the view, but the QuerySet or rather it's lookup. Sure I could use the raw SQL query, but that feels somewhat unsave and may have side effects, due to Django not caching the query.

I will look into it. But that means I will merge my other commit, branch that refactored the view.

**Comment by codingjoe** [comment]
@applegrew I'm not finished yet, but I did an exhausting amount of refactoring. With success.

Most notably:
- caching is save, registration happens during widget.render

**Comment by codingjoe** [comment]
Closed, in favour of v5 release branch.

**Pull request closed without merging**
