### PR TITLE
fix to #544

### PR DESCRIPTION
**Pull request by mfrasca**
I'm opening this PR as work in progress.  the underlying idea is better visibility of the solving process for issue #544 .

### CODE REVIEW

**Comment by mfrasca** [comment]
this patch triggers 4 failures, all after a simulated `click`.  three of them fail because the tests assert different results on different widgets, but the result is now `Please enter 2 or more characters`, which is possibly the correct behaviour.

**Comment by codingjoe** [comment]
@mfrasca I added one commit myself to change how the defaults are set. Would you mind reviewing it?

**Comment by mfrasca** [comment]
looks good to me.  about testing, do you think you have all cases covered?  I do miss some technical documentation, like the role of the parameters, or hints to "future me" because in a couple of weeks I will know nothing of this code.  let me add, I'm quite happy about the process we followed.  :+1: 

whenever I am back to using these widgets for the M2M, I'll review the docs and suggest additions if I miss anything.

**Comment by marojenka** [comment]
Hi. Just as a remark. Enabling default value for `data-minimum-input-length` changed default behaviour so some ppl might be confused by this (I was a bit) as it was made in patch release.
Happy to have it regardless.

**Comment by mfrasca** [comment]
> Hi. Just as a remark. Enabling default value for `data-minimum-input-length` changed default behaviour so some ppl might be confused by this (I was a bit) as it was made in patch release.
> Happy to have it regardless.

may I suggest … do you think you can provide the unit test cases you are interested in?
as to guarantee that the behaviour stays frozen.

**Pull request merged**
