### PR TITLE
allow custom object labels

### PR DESCRIPTION
**Pull request by michaelkuty**
we need have ability to change label in choices, but i don't know if that solution is best way for do that, what you think about this implementation ?

### CODE REVIEW

**Comment by codingjoe** [comment]
@michaelkuty good point. But I don't like reinventing the wheel. A field already has this method and it gets used by the `ModelChoiceIterator`. For that matter, the view should use the iterator to create the choices.
Would you like to implement that?

**Comment by michaelkuty** [comment]
yes, I know about this method on field, but i don't know how get field in the view where is just widget now

**Comment by codingjoe** [comment]
Yes, similar to how we get the queryset https://github.com/applegrew/django-select2/blob/master/django_select2/forms.py#L373
choices.field is the field.
But I would rather use the iterator's `choice` method. Sadly I don't know if it is a good idea to pickle the entire field.
It wasn't a good idea to pickle the entire widget.

**Comment by michaelkuty** [comment]
Yes, i think too, that pickling whatever to session is not good idea, but what you thinking about geting whole method from field ? something like

    self.label_from_instance = field.label_from_instance

and calling it from view ?

**Comment by michaelkuty** [comment]
this is seems to be much better solution

**Comment by michaelkuty** [comment]
what you thinking about this ?

**Comment by codingjoe** [comment]
@michaelkuty as you didn't add it to the cache, I won't work. Problem is you'd have to add the entire field to the cache.

Maybe it is a good idea to a method here. BTW, you can just add your own view and change that behavior. I did it in a lot of my projects.

**Comment by michaelkuty** [comment]
this actually works for me now, we use only specific method which we calls when we need object representation
why you create new release of solution which works ? I think that is because you want simplify behavior, but without removing features which we needs !
for example we have page and folder and we need render tree structure (page 1 > page 2)
but without changing object representation !
without ability to changing label anyhow is this project not usable.. 

why i need create new view ? while i can create field which has responsibility to render field choices ? why we need move logic to new place ?

**Comment by michaelkuty** [comment]
ok new implementation uses field, but I don't now if is pretty clear code

**Comment by codingjoe** [comment]
@michaelkuty you can't not pickle a field. If you do that, they queryset of a ModelChoiceField will be fetched and pickled entirely.

I think I can live with the first version. But why don't you just build your own mixin or subclass?

**Comment by michaelkuty** [comment]
we use this plugin across large leonardo ecosystem(https://github.com/django-leonardo/django-leonardo) and last thing to do is overrides stuff which works on <5 version
ok but this is last option to getting things done :-( sorry but this is so sad

**Comment by michaelkuty** [comment]
and also thanks with making this solution

**Comment by michaelkuty** [comment]
ok i made integration via widget method as you said its small override(but will be nice to have this feature in code library), yes i know this method is on field but obviously you create widget with custom search_fields and you have best place for do this
https://github.com/django-leonardo/django-leonardo/commit/5a63c7354e86bd9c5c6a5f91ca4a9c4aec5b0c0e

**Comment by codingjoe** [comment]
@michaelkuty this still won't work. You would see that if you'd just added tests.
I'm not so sure about a good implementation yet. I won't add the field to the cache, that much is certain.
I'll close the PR. Please overwrite in you own code to implement this feature.

I added a ticket, if more people support it, I'll add it.

**Pull request closed without merging**
