### PR TITLE
fix: dependent fields do not work when the form is an inline admin form

### LINKED ISSUE #380: dependent fields do not work when the form is an inline admin form
I found a problem with dependent_fields when using django-select2 as an inline admin form. The result is that the select options are never updated to filter based on the dependent field.
I created #379 to resolve this

### PR DESCRIPTION
**Pull request by jnoortheen**
resolves #380

I have the `inline-related` class name hard coded but even then it is less hackish.

### CODE REVIEW

**Comment by codingjoe** [comment]
Hi @jnoortheen 
Thanks for the Pull-Request! This really is a bug that we should fix.
For now, can you please do me a favor and make sure the tests pass. Please also add a test for the prefix behavior, to ensure we never break it in the future. If you need any help, please let me know.
Thanks!
Johannes

**Comment by jnoortheen** [comment]
sure I will check the failing tests and try to add a test for this change.

**Comment by jnoortheen** [comment]
Sure I will update it.

**Comment by codingjoe** [comment]
Just let me know when you are done.
I would use the fact, that field names can not include `-` but `From.add_prefx` and `Form.add_initial_prefix` both use `-` as a separator. Unless overridden it's safe to assume `rsplit('-',1)[-1]` is the field name.

**Comment by codingjoe** [comment]
Since this PR hasn't been active for almost a year, I will close it for now. Please let me know if you want to pickup the work. I am happy to reopen it.

**Comment by aghdaeea** [comment]
Could someone merge the changes? this is an important bug.

thanks

**Pull request closed without merging**
