### PR TITLE
Fix HeavySelect2MultipleWidget

### PR DESCRIPTION
**Pull request by quantum5**
Fixed a "selector not found" error similar to the one fixed in 2bf42c5bdabaa22b90878d9cd91a5912c6a6720a.

### CODE REVIEW

**Comment by codingjoe** [comment]
@quantum5 can you add a test for the error you described?

**Comment by iwaszko** [comment]
+1, after upgrading to the 4.3.1 version od django_select2 I also got this "Uncaught ReferenceError: selector is not defined" error and applying patch from this pull request seems to fix it.

My use case is quite complicated since I use django_select2 together with patched version of django-inplaceedit, but the above mentioned error is happening wherever I use HeavySelect2MultipleWidget.

**Comment by iwaszko** [comment]
OK, I was able to create a failing test that this commit fixes. I'm quite new to github tho and unsure how to proceed but I guess I'll just create another pull request with that test and this fix, but of course credit goes to @quantum5

**Comment by iwaszko** [comment]
Please see #175

**Comment by skolsuper** [comment]
Can we get this fix into a minor release 4.3.2?  I want to use django_select2 in another package and I don't want to have to use an editable dependency in requirements (if that is even possible?)

**Comment by quantum5** [comment]
Editable dependency in requirements.txt is possible.

**Comment by skolsuper** [comment]
What about setup.py `install_requires`?

**Comment by codingjoe** [comment]
@applegrew I think we should create a new release from master.

**Comment by applegrew** [comment]
Ok.

Regards,
Nirupam
-------------------------------------------------------------------------
Cink <http://cink.applegrew.com> | Home <http://www.applegrew.com> |  Git
<https://github.com/applegrew/> | Blog <http://blog.applegrew.com> |  MaapIn
<http://www.maap.in>

**Comment by applegrew** [comment]
I am just about to publish version 5.0.0 based on master code. @codingjoe Please update the Changelog.md with important changes that have been made. Currently I have put a very generic statement.

**Comment by codingjoe** [comment]
@applegrew why a new major version? There were just minor fixes. I've been on a version 5 branch since forever. That will be very miss leading. Can you please pull the version, tho this isn't really nice.

Just create a new fix release. There haven't been any features added. I'll write a Changelog.

**Comment by codingjoe** [comment]
BTW, it would be cool if you could add me as a colaborator on pypi. That we I can release myself and we can avoid this confusion in the future.

**Comment by applegrew** [comment]
Oops. Removed v5 from PyPi.

**Comment by codingjoe** [comment]
Ok master is released in 4.3.2

**Pull request closed without merging**
