### PR TITLE
Force unicode for widget choice labels

### PR DESCRIPTION
**Pull request by bubenkoff**

### CODE REVIEW

**Comment by codingjoe** [comment]
@bubenkoff that doesn't work on python 3. What exactly is the point of this patch?

**Comment by bubenkoff** [comment]
i misread the docs, sorry, that's not fixed

**Comment by bubenkoff** [comment]
the force_text is called for the labels because they can be translation proxies, for obvious reasons

**Comment by codingjoe** [comment]
@bubenkoff thx!

**Comment by bubenkoff** [comment]
could you please make a new release?

**Pull request merged**
