### PR TITLE
added migrations for django 1.7+

### PR DESCRIPTION
**Pull request by douwevandermeij**
Generated with Django 1.8

### CODE REVIEW

**Comment by codingjoe** [comment]
@douwevandermeij I don't know if I really want to fix this, because the model is going to be removed anyway. I'll think about it a little. The new solution is almost ready. Than I will bare the migration in mind.

**Comment by douwevandermeij** [comment]
That's ok, for now I'll use the github version in my project.

**Comment by codingjoe** [comment]
@douwevandermeij while we're at it, how's the current master working on django 1.8?

**Comment by douwevandermeij** [comment]
I didn't found any problem yet actually :)

**Comment by codingjoe** [comment]
No longer needed in v5

**Pull request closed without merging**
