### PR TITLE
Fix build_attrs() params to support Django 1.11

### PR DESCRIPTION
**Pull request by yuvadm**
This PR overrides #343 and adds testing support in `tox.ini`

### CODE REVIEW

**Comment by yuvadm** [comment]
Not sure what to make of the CI tests, looks like this fix isn't enough?

**Comment by codingjoe** [comment]
@yuvadm please remove 1.9 since it's no longer supported.

**Comment by yuvadm** [comment]
@codingjoe done, updated and squashed

**Comment by codingjoe** [comment]
@yuvadm actually this will not fix the issue I spend a couple of ours yesterday digging into the code changes in Django. I am working on a patch today. Thanks for the effort, I am eager to update this package to support 1.11 LTS too.

**Comment by yuvadm** [comment]
@codingjoe no problem, thanks!

**Comment by codingjoe** [comment]
@yuvadm there you go https://github.com/applegrew/django-select2/pull/345

**Pull request closed without merging**
