### PR TITLE
queryset from choices

### PR DESCRIPTION
**Pull request by predatell**

### CODE REVIEW

**Comment by codingjoe** [comment]
@predatell could you elaborate a bit more on this use case?

**Comment by codingjoe** [comment]
Closed: **This issue has been inactive for an extended period of time. Please reopen the issue if it is still relevant.**

**Comment by predatell** [comment]
I want to use `ModelSelect2Widget` with `ModelChoiceField`. I set `queryset` to `ModelChoiceField`, so I don't want to add the same `queryset` to `ModelSelect2Widget`. `ModelSelect2Widget` can take it from `self.choices.queryset`. Example how do I use it:
`item = forms.ModelChoiceField(queryset=MyModel.objects.filter(is_active=True), required=False, widget=ModelSelect2Widget)`

**Comment by codingjoe** [comment]
@predatell good idea. Can you please add test for you scenario, to make sure it works and won't break in future releases? Thanks, Joe

**Comment by predatell** [comment]
I have removed `model` for `ModelSelect2Widget` in tests where related `ModelChoiceField` already has `queryset`. So `ModelSelect2Widget` takes `queryset` from related `ModelChoiceField`.

**Comment by codingjoe** [comment]
Released in [7.1.0](https://github.com/applegrew/django-select2/releases/tag/7.1.0)

**Pull request merged**
