### PR TITLE
WIP: adding queryset_transform kwarg to ModelSelect2Mixin

### LINKED ISSUE #510: ModelSelect2Widget: sorting
I need an annotation to change the ordering of the search results for the `ModelSelect2Widget`, to prioritize matches starting with the search term over substring matches. Just sorting by name can result in ordering like this with `term = 'cat'`:
```
a small cat
both big cats
cat
```

while I would like to have
```
cat
a small cat
both big cats
```

I implemented it using this customization of `ModelSelect2Widget`:
```python
class PrioritizeStartsWithWidget(ModelSelect2Widget):
    def filter_queryset(self, term, queryset, **dependent_fields):
        qs = super().filter_queryset(term, queryset, **dependent_fields)
        return  qs.annotate(
            starts_with_order=Case(
                When(name__istartswith=term, then=Value(1)),
                default=Value(0),
                output_field=IntegerField()
            ),
        ).order_by("-starts_with_order", "name")
```

While this works it might be nice to be able to add such a transformation without having to create a custom class. I'm not sure what would be a good/flexible API, but something like this would suit my needs:
```
class MyForm(forms.ModelForm):
   field = forms.ModelSelectField(...
       widget=ModelSelect(
           queryset=Model.objects.all(), 
           queryset_transform=lambda queryset, term: queryset.annotate(....).order_by(...)
       )
    )
```

The provided callable should be executed as part of `filter_queryset`

### PR DESCRIPTION
**Pull request by jieter**
fixes #510 

~~I did not think of the issue that assigning a callable to a class attribute will make it a bound method, which is annoying as it requires a 'self' argument as first argument.~~

~~When writing this: It might also be desirable. It allows access to the widget, so the callable must take 3 arguments: `widget, queryset, term`.~~

### CODE REVIEW

**Comment by jieter** [comment]
Apparently my memory identified this callable-assigment as a problem, while in reality it was not. Cleaned up the implementation a bit and added a test.

**Comment by codingjoe** [comment]
@jieter thanks for the example, I think now I understand your use case better.
I am wondering tho, why don't you just pass the modified queryset to begin with? Like so:

```python
Select2ModelWidget(queryset=MyMode.objects.all().annotate(sort_order=F('title')).order_by('-sort_order'))
```

This should have the same effect, should it not?

**Comment by jieter** [comment]
Wouldn't that be equivalent to `.order_by('-title')` ? I think I need the actual search term to prefer records starting with it, rather than just alphabetical ordering on the title.

**Comment by codingjoe** [comment]
I think I can't follow you here. There is no difference when you specify the order for a Queryset, is there?
Why does it matter if you apply the search parameters before or after? If you lock at the actual query, there shoudn't be a difference.

**Comment by codingjoe** [comment]
```python
class MyForm(forms.ModelForm):
    location = forms.ModelChoiceField(
        queryset=Location.objects.all(),
        required=False,
        widget=ModelSelect2Widget(
            queryset=Location.objects.all().annotate(
                sort_order=Case(
                    When(name__istartswith=term, then=Value(1)), default=Value(0), output_field=IntegerField()
                    ),
                ).order_by("-sort_order", "name")
            ), 
            search_fields=['name__icontains'],
    )
```

like so?

**Comment by jieter** [comment]
`term` is not defined at field definition time.

**Comment by codingjoe** [comment]
Aaaah ok, now I see what you mean.

Please don't take this the wrong way, but this is a highly specific case. I believe writing your own subclass and overwriting `filter_queryset` is the best way to go.
Adding support for that would further drive complexity of the code base, which I want to keep as low as possible to allow smooth maintenance thought all Django versions.

Of course I am open to reconsider, but maybe you agree with my point.

**Comment by jieter** [comment]
Yes, I see, might be more trouble than it's worth. No problem!

**Comment by codingjoe** [comment]
If this is a common use case for you. Just build your own mixin. You already provided the right code for it in this PR. This should allow you to simply "configure" the callable, if this is what you need.

**Pull request closed without merging**
