### PR TITLE
Update urls.py for django 1.9 compatibility

### PR DESCRIPTION
**Pull request by TheRakken**
Fix for #235

### CODE REVIEW

**Comment by codingjoe** [comment]
@TheRakken thanks for the PR. You didn't include urls in the testapp in tests. These should be updated as well, to ensure tests running in future versions.

**Comment by TheRakken** [comment]
ok. I'm on it

**Comment by TheRakken** [comment]
Done. Let me know if I missed anything else

**Comment by codingjoe** [comment]
Thanks @TheRakken 

Released in 5.4.3

**Pull request closed without merging**
