### PR TITLE
use skip_cleanup to distribute build artifacts

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by codingjoe** [comment]
@graingert almost ;)

**Comment by graingert** [comment]
looks like it's a lint error, @codingjoe >         D100: Missing docstring in public module

**Comment by graingert** [comment]
@codingjoe this is it, for real this time

**Comment by codingjoe** [comment]
Released in [6.3.1](https://github.com/applegrew/django-select2/releases/tag/6.3.1)

**Pull request merged**
